# Generated by Django 5.1.1 on 2024-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likehome_api', '0002_profile_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
