# Generated by Django 5.1.1 on 2024-10-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likehome_api', '0006_alter_reservation_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
