# Generated by Django 5.1.1 on 2024-11-01 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likehome_api', '0007_alter_reservation_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('description', models.TextField(default='N/A')),
                ('min_rate', models.FloatField()),
                ('max_rate', models.FloatField()),
                ('currency', models.CharField(default='N/A', max_length=3)),
                ('phone_number', models.CharField(default='N/A', max_length=10)),
                ('email', models.EmailField(default='N/A', max_length=254)),
                ('website', models.CharField(default='N/A', max_length=100)),
                ('images', models.JSONField(default=list)),
                ('address', models.CharField(default='N/A', max_length=100)),
                ('city', models.CharField(default='N/A', max_length=100)),
                ('rooms', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
