# Generated by Django 5.1.1 on 2024-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likehome_api', '0008_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
