# Generated by Django 5.1.1 on 2024-11-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likehome_api', '0010_reservation_rewards_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rewards_applied',
            field=models.IntegerField(default=0),
        ),
    ]
