# Generated by Django 5.1.1 on 2024-11-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likehome_api', '0011_reservation_rewards_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='website',
            new_name='web',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='check_in',
            field=models.DateField(default='2024-11-03'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='check_out',
            field=models.DateField(default='2024-11-03'),
        ),
    ]
