# Generated by Django 5.1.1 on 2024-11-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likehome_api', '0015_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rewards_applied_cost',
            field=models.FloatField(default=0),
        ),
    ]
